name: Build packages

on:
  - workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: "/opt/termux/android-sdk"
      NDK: "/opt/termux/android-ndk"

    strategy:
      matrix:
        target_arch: [aarch64, arm, i686, x86_64]
      fail-fast: false

    steps:

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Get packages from termux-packages
        uses: actions/checkout@v3
        with:
          repository: termux/termux-packages
          path: termux-packages

      - name: Setup environment
        run: |
          # Use custom packaging properties for JekyllEx
          rm termux-packages/scripts/properties.sh termux-packages/scripts/build-bootstraps.sh
          mv termux-packages/* .
          rm -rf termux-packages
          mv properties.sh build-bootstraps.sh scripts/

      - name: Build packages
        run: ./scripts/run-docker.sh ./build-package.sh -a ${{ matrix.target_arch }} git tar make ruby libxslt libllvm coreutils binutils-libs

      - name: Store debs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: debs-${{ matrix.target_arch }}
          path: output
